import { mainFont } from "@/utils/font";
import "./globals.css";

export const metadata = {
  title: "Marketing Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${mainFont.className} antialiased scroll-smooth py-4`}>
        {children}
      </body>
    </html>
  );
}
